# Generated by Django 6.0.2 on 2026-02-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='featured_post',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
